# Generated by Django 6.0.5 on 2026-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('EM', 'Employer'), ('JS', 'Job-Seeker')], max_length=20),
        ),
    ]
