# Generated by Django 6.0.5 on 2026-07-30 07:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='photo'),
        ),
    ]
