# Generated by Django 6.0.5 on 2026-07-30 07:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_jobseeker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
